[build]
command = "API_HOST=https://layers-api-staging.planninglabs.nyc yarn build --environment=production"

[build]
command = "API_HOST=https://layers-api-data.planninglabs.nyc yarn build --environment=production"

[context.master]
command = "yarn build --environment=production"
